services:
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: unless-stopped
    ports: 
      - "${LOKI_PORT}:${LOKI_PORT}"
    environment:
      - LOKI_PORT=${LOKI_PORT}
    command: -config.file=/etc/loki/local-config.yaml -config.expand-env=true
    volumes: 
      - ./local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - log_monitor
  
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - log_monitor

networks:
  log_monitor:
    name: log_monitor
    driver: bridge

volumes:
  loki-data:
  grafana-data: