[job-local "archive-log-app1"]
schedule = 0 0 0 * * *
command = /bin/sh /script/archive_log_app1.sh

; [job-local "archive-log-db1"]
; schedule = 0 0 1 * * *
; command = /bin/sh /script/archive_log_db1.sh

; [job-local "archive-db1"]
; schedule = 0 0 1 * * *
; command = /bin/sh /script/archive_db1.sh

; [job-local "scheduler-status"]
; schedule = 0 0 1 * * *
; command = /bin/sh /script/scheduler_status.sh